# Generated by Django 5.2.7 on 2025-10-31 11:19

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=15, verbose_name='手机号')),
                ('account_id', models.CharField(default=users.models.generate_user_id, max_length=8, unique=True, verbose_name='账户ID')),
                ('account_avatar', models.ImageField(blank=True, help_text='支持 JPG, PNG 格式，建议尺寸 200x200 像素', null=True, upload_to=users.models.user_avatar_upload_path, verbose_name='账户头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
    ]
