# Generated by Django 5.2.7 on 2025-11-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_genericmessage_delete_gneral_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmessage',
            name='content_type',
            field=models.CharField(default='text', max_length=50, verbose_name='内容类型'),
        ),
    ]
