# Generated by Django 5.2.7 on 2026-01-04 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_genericmessage_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericmessage',
            options={'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.RemoveIndex(
            model_name='genericmessage',
            name='sender_receiver_thread_idx',
        ),
        migrations.AddField(
            model_name='genericmessage',
            name='thread_id',
            field=models.CharField(db_index=True, default='system', help_text='格式: 小用户ID_大用户ID', max_length=64, verbose_name='会话ID'),
        ),
        migrations.AlterField(
            model_name='genericmessage',
            name='content_type',
            field=models.CharField(default='text', max_length=20, verbose_name='内容类型'),
        ),
        migrations.AlterField(
            model_name='genericmessage',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='genericmessage',
            name='extensions',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展数据'),
        ),
        migrations.AddIndex(
            model_name='genericmessage',
            index=models.Index(fields=['thread_id', '-created_at'], name='idx_thread_time'),
        ),
        migrations.AddIndex(
            model_name='genericmessage',
            index=models.Index(fields=['receiver', 'is_read', '-created_at'], name='idx_receiver_unread'),
        ),
        migrations.AddIndex(
            model_name='genericmessage',
            index=models.Index(fields=['sender', '-created_at'], name='idx_sender_time'),
        ),
    ]
