# Generated by Django 5.2.7 on 2026-05-29 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_forum_post_comment_postmedia_forumbanlist_postlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_forums', to=settings.AUTH_USER_MODEL, verbose_name='Forum管理员列表'),
        ),
        migrations.AddField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_forums', to=settings.AUTH_USER_MODEL, verbose_name='Forum成员列表'),
        ),
    ]
