# Generated by Django 5.2.7 on 2026-05-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_forum_admins_forum_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='forum',
            name='icon_base64',
            field=models.TextField(blank=True, verbose_name='版块图标Base64'),
        ),
    ]
