# Generated by Django 5.2.7 on 2026-05-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_forum_icon_url_forum_icon_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.TextField(blank=True, null=True, verbose_name='封面图Base64'),
        ),
    ]
